[ansible] monitor upgrade stuff

diff --git a/base/ansible/playbooks/upgrade-monitoring.yaml b/base/ansible/playbooks/upgrade-monitoring.yaml
--- a/base/ansible/playbooks/upgrade-monitoring.yaml
+++ b/base/ansible/playbooks/upgrade-monitoring.yaml
@@ -2,12 +2,30 @@
 - hosts: c
   strategy: free
   tasks:
+    - name: checks
+      shell: "uptime -p &&
+        cd ~/code/pats && echo git sha: $(git rev-parse HEAD) &&
+        echo image version: $(cat ~/dependencies/image_version) kernel: $(uname -r) $(lsb_release -d) &&
+        lscpu | grep 'Model name' &&
+        if [ -f /var/run/reboot-required ]; then echo 'reboot required'; fi &&
+        if [ -f '/home/pats/pats/xml/pats.xml' ] ; then echo 'Custom pats.xml found' ; fi &&
+        if [ -f '/home/pats/pats/flags/disable_baseboard' ] ; then echo 'Baseboard DISABLED' ; fi &&
+        if [ -e '/dev/baseboard' ] ; then echo 'Baseboard: OK' ; else echo 'Baseboard: NOT DETECTED' ; fi &&
+        if [ -e '/dev/pats_mm0' ] ; then echo 'MultiModule: OK' ; else echo 'MultiModule: NOT DETECTED' ; fi &&
+        echo RealSense: $(lsusb | grep RealSens) &&
+        echo 4G: $(lsusb | grep 'E353/E3131')"
+      register: output_checks
+    - debug: var=output_checks.stdout_lines
+    - name: Run clean hd script
+      shell: "(cd ~/code/pats/base/data_processing/ && ./clean_hd.py)"
     - name: Disable all pats daemons
       ansible.builtin.file:
         path: ~/pats/flags/disable
         state: touch
     - name: Kill (auto restart) executor process
       shell: "killall executor || true"
+    - name: Kill (auto restart) pats process
+      shell: "killall pats || true"
     - name: Pull pats
       git:
         repo: git@github.com:pats-drones/pats.git
